Repository DartsArmaMods/AimForTheBushes, pull requests merged in 2024-11, with the labels that each got.

#46 General - Use ACE Common's `Enabled` key
  addons/helocast/initSettings.inc.sqf
  addons/helocast/stringtable.xml
  addons/staticline/initSettings.inc.sqf
  addons/staticline/stringtable.xml
Labels: kind/cleanup, area/translations

#47 General - Sort stringtables, add missing key
  addons/common/stringtable.xml
  addons/helocast/stringtable.xml
  addons/main/stringtable.xml
  addons/staticline/stringtable.xml
Labels: kind/cleanup

#48 Helocast - Add parameter to `fnc_loadBoat` to ignore ramp state
  addons/helocast/functions/fnc_canLoadBoat.sqf
  addons/helocast/functions/fnc_loadBoat.sqf
  docs/wiki/frameworks/helocast.md
  include/z/ace/addons/main/script_debug.hpp
Labels: kind/documentation, kind/enhancement

#51 Common - Make level ramps count as open
  addons/compat_cup_vehicles/CfgVehicles.hpp
  addons/compat_gm/CfgVehicles.hpp
  addons/compat_rhs_usaf/CfgVehicles.hpp
  addons/compat_sog/cfg/helicopters.hpp
  addons/compat_sog/script_macros.hpp
  addons/compat_usaf_utility/CfgVehicles.hpp
  docs/wiki/frameworks/common.md
Labels: kind/documentation, kind/enhancement

#52 Common - Improve caching
  addons/common/XEH_postInit.sqf
  addons/common/XEH_preInit.sqf
  addons/common/functions/fnc_getRampAnimations.sqf
Labels: kind/bug-fix, kind/enhancement

#50 Helocast - Improve boat unloading
  addons/common/XEH_postInit.sqf
  addons/helocast/CfgEventHandlers.hpp
  addons/helocast/XEH_PREP.hpp
  addons/helocast/XEH_postInit.sqf
  addons/helocast/XEH_preInit.sqf
  addons/helocast/functions/fnc_loadBoat.sqf
  addons/helocast/functions/fnc_unloadBoat.sqf
  addons/helocast/functions/fnc_unloadBoatPFH.sqf
  addons/main/script_macros.hpp
Labels: kind/bug-fix, kind/enhancement

#54 Helocast - Increase maximum auto load distance
  addons/helocast/XEH_preInit.sqf
Labels: kind/enhancement

#55 Compatibility - Add Hatchet Compat
  .vscode/sqfvm-lsp/ls-ignore.txt
  addons/compat_hatchet/$PBOPREFIX$
  addons/compat_hatchet/CfgVehicles.hpp
  addons/compat_hatchet/config.cpp
  addons/compat_hatchet/script_component.hpp
  docs/README.md
Labels: kind/enhancement, area/compatibility

#56 Compatibility - Add JLTS and 3AS Compats
  .hemtt/launch.toml
  addons/common/CfgVehicles.hpp
  addons/compat_jlts/$PBOPREFIX$
  addons/compat_jlts/CfgVehicles.hpp
  addons/compat_jlts/config.cpp
  addons/compat_jlts/script_component.hpp
  addons/compat_tas/$PBOPREFIX$
  addons/compat_tas/CfgVehicles.hpp
  addons/compat_tas/config.cpp
  addons/compat_tas/script_component.hpp
  docs/README.md
Labels: kind/enhancement, area/compatibility

#57 Rename workspace
  AimForTheBushes.code-workspace
Labels: area/tools

#60 General - Remove unused includes
  include/a3/ui_f/hpp/defineCommon.inc
  include/a3/ui_f/hpp/defineCommonGrids.inc
  include/a3/ui_f/hpp/defineResincl.inc
  include/a3/ui_f/hpp/defineResinclDesign.inc
  include/a3/ui_f/ui_f_curator/ui/defineResinclDesign.inc
Labels: area/tools
