Repository DartsArmaMods/AimForTheBushes, pull requests merged in 2024-10, with the labels that each got.

#36 General - Lowercase addon names and pboprefixes
  addons/compat_optre/$PBOPREFIX$
  addons/compat_optre_fc/$PBOPREFIX$
  addons/loadorder/$PBOPREFIX$
  addons/loadorder/script_component.hpp
  addons/staticline/script_component.hpp
  extra/example_addon/$PBOPREFIX$
  extra/example_addon/script_component.hpp
Labels: bug

#37 Helocast - Add compatibility for S.O.G. Helicopters
  addons/compat_sog/CfgVehicles.hpp
  addons/compat_sog/cfg/helicopters.hpp
  addons/compat_sog/cfg/parachutes.hpp
  addons/compat_sog/script_component.hpp
  addons/compat_sog/script_macros.hpp
  addons/helocast/functions/fnc_canLoadBoat.sqf
  extra/example_subaddon/script_component.hpp
Labels: enhancement

#38 Static Line - Add public function for creating a jump waypoint
  addons/staticline/XEH_PREP.hpp
  addons/staticline/functions/fnc_addWaypoint.sqf
  docs/frameworks/staticline-framework.md
Labels: enhancement

#42 General - Change URLs to match organization
  .github/PULL_REQUEST_TEMPLATE.md
  README.md
  addons/main/script_mod.hpp
  addons/main/stringtable.xml
  docs/README.md
Labels: kind/cleanup

#41 Common - Improve automatic detection of passengers
  addons/common/CfgVehicles.hpp
  addons/common/functions/fnc_getPassengers.sqf
  addons/compat_csla/CfgVehicles.hpp
  addons/compat_cup_vehicles/CfgVehicles.hpp
  addons/compat_ls/CfgVehicles.hpp
  addons/compat_optre/CfgVehicles.hpp
  addons/compat_optre_fc/CfgVehicles.hpp
  addons/compat_rhs_usaf/CfgVehicles.hpp
  addons/compat_sog/cfg/helicopters.hpp
  addons/compat_tf373/CfgVehicles.hpp
  addons/compat_uk3cb/CfgVehicles.hpp
  addons/main/script_macros.hpp
  docs/frameworks/common-functionality.md
Labels: kind/enhancement, area/compatibility

#43 Compabitility - Add Global Mobilization plane support for Static Line
  addons/compat_gm/CfgVehicles.hpp
Labels: kind/enhancement, area/compatibility

#45 Docs - Delete current docs, moved to GitBook
  docs/features/helocast-feature.md
  docs/features/staticline-feature.md
  docs/frameworks/common-functionality.md
  docs/frameworks/helocast-framework.md
  docs/frameworks/staticline-framework.md
Labels: kind/documentation
